import { Button } from "./components/ui/button";
import { Link } from "react-router-dom";
export default function App() {
  const cards = [
    {
      title: "Candidate Profiles",
      desc: "This module is responsible for collecting and managing detailed candidate information. It stores basic details such as name and email, along with job preferences including preferred industries, roles, skills, experience level, location, and job type. These preferences form the foundation of the matching system and are used to personalize job recommendations for each candidate.",
      gradient: "from-pink-500 via-red-500 to-yellow-500",
      link:"/candidatesform"
    },
    {
      title: "Job Listings",
      desc: "This section represents a centralized repository of job opportunities collected from multiple external job platforms. Each job record includes the job title, company name, industry or domain, required skills, experience level, job description, location, and source URL. Storing jobs in a structured format allows efficient searching, filtering, and matching.",
      gradient: "from-purple-500 via-indigo-500 to-blue-500",
      link:"/jobtype"
    },
    {
      title: "Job Scraping",
      desc: "The job scraping module is responsible for ingesting job data from public job boards such as LinkedIn or Indeed. It fetches a limited and controlled number of job listings, extracts relevant fields, and converts them into structured job records. Ethical scraping practices are followed to avoid excessive requests and ensure compliance with platform guidelines.",
      gradient: "from-green-400 via-emerald-500 to-teal-500",
      link: "/crawler"
    },
    {
      title: "Matching Engine",
      desc: "This core module matches candidates with suitable jobs using rule-based and mathematical techniques. Jobs are scored based on skill overlap, keyword similarity, preferred roles, industries, and optional preferences like location or experience. The scoring logic is transparent and explainable, ensuring that recommendations are logical and easy to understand.",
      gradient: "from-orange-400 to-yellow-300",
      link: "/match"
    },
    {
      title: "Admin Dashboard",
      desc: "The admin dashboard allows administrators to select a candidate and view all recommended jobs generated by the matching engine. It provides visibility into how jobs are matched and helps validate the accuracy of the system. This interface can be extended to support analytics, filters, or manual overrides if required.",
      gradient: "from-cyan-500 via-sky-500 to-blue-600",
      link:"/admin"
    },
  
  ];

  return (
    <div className="min-h-screen w-full relative raleway-500 ">
      <h1 className="text-black z-40  lg:text-xl sticky top-0 font-bold backdrop-blur-3xl bg-white/40  text-md    text-center">
        <div className="p-5">
          Job Preference Matching System
        </div>
      </h1>

      <div className="grid gap-3 pt-5 sm:grid-cols-2 lg:grid-cols-2 px-4">
        {cards.map((card, idx) => (
          <div
            key={idx}
            className={`rounded-xl relative p-6 lg my-1 min-h-50 bg-gradient-to-br ${card.gradient} shadow-xl transition-transform`}
          >
            <h2 className="text-white text-2xl font-bold mb-3">
              {card.title}
            </h2>
            <p className="text-white/90 text-sm leading-relaxed mb-15">
              {card.desc}
            </p>
            {card.link?<Link to={`${card.link}`}>
            <Button variant={"secondary"} className="w-full absolute bottom-5 transition cursor-pointer  h-10 flex justify-center items-center font-semibold w-max px-10 rounded-full my-2">
              See Details
            </Button>
            </Link>:<Button variant={"secondary"} className="w-full absolute bottom-5 transition cursor-pointer  h-10 flex justify-center items-center font-semibold w-max px-10 rounded-full my-2">
              See Details
            </Button>}
          </div>
        ))}
         <div
            className={`rounded-xl p-6 lg my-1  flex justify-center items-center min-h-50 bg-gradient-to-br transition-transform`}
          >
            <h2 className="text-black text-2xl text-center w-full  font-bold mb-3">
              Made by Soumya Jaiswal 
            </h2>
          </div>
      </div>
    </div>
  );
}
